//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHexaEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfHexaEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have reached the end of file. Do you want append one byte ? This operation cannot be canceled if you continue..
        /// </summary>
        public static string AppendByteConfirmationString {
            get {
                return ResourceManager.GetString("AppendByteConfirmationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bookmarks.
        /// </summary>
        public static string BookmarksString {
            get {
                return ResourceManager.GetString("BookmarksString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Byte action.
        /// </summary>
        public static string ByteActionString {
            get {
                return ResourceManager.GetString("ByteActionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Byte.
        /// </summary>
        public static string ByteString {
            get {
                return ResourceManager.GetString("ByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel long process.
        /// </summary>
        public static string CancelLongProcessString {
            get {
                return ResourceManager.GetString("CancelLongProcessString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to cancel long process..
        /// </summary>
        public static string CancelLongProcessToolTipString {
            get {
                return ResourceManager.GetString("CancelLongProcessToolTipString", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can't convert this string to long..
        /// </summary>
        public static string ConvertStringToLongErrorString
        {
            get {
                return ResourceManager.GetString("ConvertStringToLongErrorString", resourceCulture);
            }
        }     
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string CancelString {
            get {
                return ResourceManager.GetString("CancelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear bookmark.
        /// </summary>
        public static string ClearBookMarkString {
            get {
                return ResourceManager.GetString("ClearBookMarkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear.
        /// </summary>
        public static string ClearString {
            get {
                return ResourceManager.GetString("ClearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to go to at position..
        /// </summary>
        public static string ClickToGoAtPositionString {
            get {
                return ResourceManager.GetString("ClickToGoAtPositionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        public static string CloseString {
            get {
                return ResourceManager.GetString("CloseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy as ASCII.
        /// </summary>
        public static string CopyAsASCIIString {
            get {
                return ResourceManager.GetString("CopyAsASCIIString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy as decimal.
        /// </summary>
        public static string CopyAsDecimalString {
            get {
                return ResourceManager.GetString("CopyAsDecimalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy as hexadecimal.
        /// </summary>
        public static string CopyAsHexadecimalString {
            get {
                return ResourceManager.GetString("CopyAsHexadecimalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TBL string (character file loaded).
        /// </summary>
        public static string CopyAsTBLString {
            get {
                return ResourceManager.GetString("CopyAsTBLString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy selection as ....
        /// </summary>
        public static string CopySelectionAsString {
            get {
                return ResourceManager.GetString("CopySelectionAsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Count of.
        /// </summary>
        public static string CountOfString {
            get {
                return ResourceManager.GetString("CountOfString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default TBL.
        /// </summary>
        public static string DefaultTBLString {
            get {
                return ResourceManager.GetString("DefaultTBLString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string DeleteString {
            get {
                return ResourceManager.GetString("DeleteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string DescriptionString {
            get {
                return ResourceManager.GetString("DescriptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 00=&lt;NUL&gt;
        ///01=&lt;SOH&gt;
        ///02=&lt;STX&gt;
        ///03=&lt;ETX&gt;
        ///04=&lt;PF&gt;
        ///05=&lt;HT&gt;
        ///06=&lt;LC&gt;
        ///07=&lt;DEL&gt;
        ///08=&lt;GE&gt;
        ///09=&lt;RLF&gt;
        ///0A=&lt;SMM&gt;
        ///0B=&lt;VT&gt;
        ///0C=&lt;FF&gt;
        ///0D=&lt;CR&gt;
        ///0E=&lt;SO&gt;
        ///0F=&lt;SI&gt;
        ///10=&lt;DLE&gt;
        ///11=&lt;DC1&gt;
        ///12=&lt;DC2&gt;
        ///13=&lt;TM&gt;
        ///14=&lt;RES&gt;
        ///15=&lt;NL&gt;
        ///16=&lt;BS&gt;
        ///17=&lt;IL&gt;
        ///18=&lt;CAN&gt;
        ///19=&lt;EM&gt;
        ///1A=&lt;CC&gt;
        ///1B=&lt;CU1&gt;
        ///1C=&lt;IFS&gt;
        ///1D=&lt;IGS&gt;
        ///1E=&lt;IRS&gt;
        ///1F=&lt;IUS&gt;
        ///20=&lt;DS&gt;
        ///21=&lt;SOS&gt;
        ///22=&lt;FS&gt;
        ///23=.
        ///24=&lt;BYP&gt;
        ///25=&lt;LF&gt;
        ///26=&lt;ETB&gt;
        ///27=&lt;ESC&gt;
        ///28=.
        ///29=.
        ///2A=&lt;SM&gt;
        ///2B=&lt;CU2&gt;
        ///2C=.
        ///2D=&lt;ENQ&gt;
        ///2E=&lt;ACK&gt;
        ///2F=&lt;BEL&gt;
        ///30=.
        ///31=.
        ///32=&lt;SYN&gt;
        ///33=.
        ///34=&lt;PN&gt;
        ///35=&lt;RS&gt;
        ///36=&lt;UC&gt;
        ///37=&lt;EOT&gt;
        ///38 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string EBCDIC {
            get {
                return ResourceManager.GetString("EBCDIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 00=.
        ///01=.
        ///02=.
        ///03=.
        ///04=.
        ///05=.
        ///06=.
        ///07=.
        ///08=.
        ///09=.
        ///0A=.
        ///0B=.
        ///0C=.
        ///0D=.
        ///0E=.
        ///0F=.
        ///10=.
        ///11=.
        ///12=.
        ///13=.
        ///14=.
        ///15=.
        ///16=.
        ///17=.
        ///18=.
        ///19=.
        ///1A=.
        ///1B=.
        ///1C=.
        ///1D=.
        ///1E=.
        ///1F=.
        ///20=.
        ///21=.
        ///22=.
        ///23=.
        ///24=.
        ///25=.
        ///26=.
        ///27=.
        ///28=.
        ///29=.
        ///2A=.
        ///2B=.
        ///2C=.
        ///2D=.
        ///2E=.
        ///2F=.
        ///30=.
        ///31=.
        ///32=.
        ///33=.
        ///34=.
        ///35=.
        ///36=.
        ///37=.
        ///38=.
        ///39=.
        ///3A=.
        ///3B=.
        ///3C=.
        ///3D=.
        ///3E=.
        ///3F=.
        ///40=.
        ///41=.
        ///42=.
        ///43=.
        ///44=.
        ///45=.
        ///46=.
        ///47=.
        ///48=.
        ///49=.
        ///4A=¢
        ///4B=.
        ///4C=&lt;
        ///4D=(
        ///4E=+
        ///4F=|
        ///50=&amp;
        ///51=.
        ///52=.
        ///53=.
        ///54=.
        ///55 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string EBCDICNoSpecialChar {
            get {
                return ResourceManager.GetString("EBCDICNoSpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;end&gt;.
        /// </summary>
        public static string EndTagString {
            get {
                return ResourceManager.GetString("EndTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter hexadecimal value ....
        /// </summary>
        public static string EnterHexValueMsgString {
            get {
                return ResourceManager.GetString("EnterHexValueMsgString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want close the current file and open : .
        /// </summary>
        public static string FileDroppingConfirmationString {
            get {
                return ResourceManager.GetString("FileDroppingConfirmationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fill selection with byte.
        /// </summary>
        public static string FillSelectionAloneString {
            get {
                return ResourceManager.GetString("FillSelectionAloneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fill selection with byte....
        /// </summary>
        public static string FillSelectionString {
            get {
                return ResourceManager.GetString("FillSelectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find All.
        /// </summary>
        public static string FindAllString {
            get {
                return ResourceManager.GetString("FindAllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find and Replace.
        /// </summary>
        public static string FindAndReplaceString {
            get {
                return ResourceManager.GetString("FindAndReplaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Byte to search.
        /// </summary>
        public static string FindByteString {
            get {
                return ResourceManager.GetString("FindByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find First.
        /// </summary>
        public static string FindFirstString {
            get {
                return ResourceManager.GetString("FindFirstString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find Last.
        /// </summary>
        public static string FindLastString {
            get {
                return ResourceManager.GetString("FindLastString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find Next.
        /// </summary>
        public static string FindNextString {
            get {
                return ResourceManager.GetString("FindNextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find all occurence of selection.
        /// </summary>
        public static string FindSelectionString {
            get {
                return ResourceManager.GetString("FindSelectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find.
        /// </summary>
        public static string FindString {
            get {
                return ResourceManager.GetString("FindString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find what:.
        /// </summary>
        public static string FindWhatString {
            get {
                return ResourceManager.GetString("FindWhatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First byte.
        /// </summary>
        public static string FirstByteString {
            get {
                return ResourceManager.GetString("FirstByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hex.
        /// </summary>
        public static string HexString {
            get {
                return ResourceManager.GetString("HexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Highlight all data find.
        /// </summary>
        public static string HighLightSettingString {
            get {
                return ResourceManager.GetString("HighLightSettingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kb.
        /// </summary>
        public static string KBTagString {
            get {
                return ResourceManager.GetString("KBTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Length.
        /// </summary>
        public static string LengthString {
            get {
                return ResourceManager.GetString("LengthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ln.
        /// </summary>
        public static string LineStatusBarTagString {
            get {
                return ResourceManager.GetString("LineStatusBarTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;ln&gt;.
        /// </summary>
        public static string LineTagString {
            get {
                return ResourceManager.GetString("LineTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Long.
        /// </summary>
        public static string LongString {
            get {
                return ResourceManager.GetString("LongString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mb.
        /// </summary>
        public static string MBTagString {
            get {
                return ResourceManager.GetString("MBTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ok.
        /// </summary>
        public static string OkString {
            get {
                return ResourceManager.GetString("OkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste operation reached the end of file. Do you want extend the file for complete operation ? This operation cannot be canceled if you continue..
        /// </summary>
        public static string PasteExtendByteConfirmationString {
            get {
                return ResourceManager.GetString("PasteExtendByteConfirmationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste from clipboard.
        /// </summary>
        public static string PasteFromClipboardString {
            get {
                return ResourceManager.GetString("PasteFromClipboardString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste without inserting.
        /// </summary>
        public static string PasteNotInsertString {
            get {
                return ResourceManager.GetString("PasteNotInsertString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Position.
        /// </summary>
        public static string PositionString {
            get {
                return ResourceManager.GetString("PositionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace All.
        /// </summary>
        public static string ReplaceAllString {
            get {
                return ResourceManager.GetString("ReplaceAllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace by byte.
        /// </summary>
        public static string ReplaceByByteString {
            get {
                return ResourceManager.GetString("ReplaceByByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace Next.
        /// </summary>
        public static string ReplaceNextString {
            get {
                return ResourceManager.GetString("ReplaceNextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace byte in selection....
        /// </summary>
        public static string ReplaceSelectionString {
            get {
                return ResourceManager.GetString("ReplaceSelectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace.
        /// </summary>
        public static string ReplaceString {
            get {
                return ResourceManager.GetString("ReplaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trim the data on the find length when replace.
        /// </summary>
        public static string ReplaceTrimSettingString {
            get {
                return ResourceManager.GetString("ReplaceTrimSettingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace with byte.
        /// </summary>
        public static string ReplaceWithByteString {
            get {
                return ResourceManager.GetString("ReplaceWithByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace with:.
        /// </summary>
        public static string ReplaceWithString {
            get {
                return ResourceManager.GetString("ReplaceWithString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select all.
        /// </summary>
        public static string SelectAllString {
            get {
                return ResourceManager.GetString("SelectAllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set bookmark.
        /// </summary>
        public static string SetBookMarkString {
            get {
                return ResourceManager.GetString("SetBookMarkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TBL.
        /// </summary>
        public static string TBLString {
            get {
                return ResourceManager.GetString("TBLString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This string are not hex.
        /// </summary>
        public static string ThisStringAreNotHexString {
            get {
                return ResourceManager.GetString("ThisStringAreNotHexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Undo.
        /// </summary>
        public static string UndoString {
            get {
                return ResourceManager.GetString("UndoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Value.
        /// </summary>
        public static string ValueString {
            get {
                return ResourceManager.GetString("ValueString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error is occurs when writing..
        /// </summary>
        public static string WritingErrorExeptionString {
            get {
                return ResourceManager.GetString("WritingErrorExeptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset zoom to 100%.
        /// </summary>
        public static string ZoomResetString {
            get {
                return ResourceManager.GetString("ZoomResetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom.
        /// </summary>
        public static string ZoomString {
            get {
                return ResourceManager.GetString("ZoomString", resourceCulture);
            }
        }
    }
}
